version: '3.4'

services:
  wpm.management.api:
    image: ${DOCKER_REGISTRY-}wpmmanagement
    build:
      context: .
      dockerfile: Wpm.Management.Api/Dockerfile

  wpm.clinic.api:
    image: ${DOCKER_REGISTRY-}wpmclinic
    build:
      context: .
      dockerfile: Wpm.Clinic.Api/Dockerfile

