name: Wpm

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Log in
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Login to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

        - name: Get current date in yyyymmdd format
          run: echo "DATE_TIME=$(date +%Y%m%d)" >> $GITHUB_ENV

        - name: 'Build and push Management container image'
          run: |
            docker build src -f src/Wpm.Management.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.DATE_TIME }}.${{ github.run_number}}
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.DATE_TIME }}.${{ github.run_number}}

        - name: 'Deploy Management to Container apps'
          uses: azure/container-apps-deploy-action@v2
          with: 
            acrName: ${{ secrets.ACR_USERNAME }}
            acrUserName: ${{ secrets.ACR_USERNAME }}
            acrPassowrd: ${{ secrets.ACR_PASSWORD }}
            containerAppName: wpm-management
            resourceGroup: wpm
            imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.DATE_TIME }}.${{ github.run_number}}
            environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug

        - name: 'Build and push Clinic container image'
          run: |
            docker build src -f src/Wpm.Clinic.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number}}
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number}}

        - name: 'Deploy Clinic to Container apps'
          uses: azure/container-apps-deploy-action@v2
          with: 
            acrName: ${{ secrets.ACR_USERNAME }}
            acrUserName: ${{ secrets.ACR_USERNAME }}
            acrPassowrd: ${{ secrets.ACR_PASSWORD }}
            containerAppName: wpm-clinic
            resourceGroup: wpm
            imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number}}
            environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug
